apiVersion: v1
kind: Service
metadata:
  name: net-hello
  labels:
    app.kubernetes.io/name: nethello
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: nethello
